capitulo 5

SELECT * FROM TALUNO;

SELECT * FROM TCONTRATO;

-- Produto cartesiano -> ERRADO
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO;

-- Correto
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO;

UPDATE TALUNO SET
NOME = 'MARCOS'
WHERE COD_ALUNO = 5;

-- Errado - coluna ambigua
SELECT COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO;

-- Uniao d atabela de aluno com contrato
SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL

FROM TALUNO ALU, TCONTRATO CON

WHERE CON.COD_ALUNO = ALU.COD_ALUNO

AND Upper(ALU.NOME) LIKE '%'

ORDER BY ALU.NOME ASC;

-- Agrupando dados de multiplas tabelas

SELECT * FROM TALUNO;
SELECT * FROM TCONTRATO;
SELECT * FROM TITEM;
SELECT * FROM TCURSO;

SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL,
       ITE.COD_CURSO, CUR.NOME AS CURSO,
       ITE.VALOR

FROM TALUNO ALU, TCONTRATO CON,
     TITEM ITE, TCURSO CUR

WHERE ALU.COD_ALUNO = CON.COD_ALUNO (+)
AND      CON.COD_CONTRATO = ITE.COD_CONTRATO (+)
AND      ITE.COD_CURSO = CUR.COD_CURSO (+)

ORDER BY CON.TOTAL DESC;

-- Adicionando o aluno 10
INSERT INTO TALUNO VALUES (10, 'PEDRO', 'NOVO HAMBURGO', NULL, 'PE', 2700, '01/10/1988');

UPDATE TALUNO SET
CIDADE = 'CAMARAGIBE'
WHERE COD_ALUNO = 10;

--Criando a tabela TDESCONTO
CREATE TABLE TDESCONTO
( CLASSE VARCHAR (1) PRIMARY KEY,
  INFERIOR NUMBER (4, 2),
  SUPERIOR NUMBER (4,2)
);

INSERT INTO TDESCONTO VALUES ('A', 00, 10);
INSERT INTO TDESCONTO VALUES ('B', 11, 15);
INSERT INTO TDESCONTO VALUES ('C', 16, 20);
INSERT INTO TDESCONTO VALUES ('D', 21, 25);
INSERT INTO TDESCONTO VALUES ('E', 26, 30);

SELECT * FROM TDESCONTO;

COMMIT;

SELECT * FROM TCONTRATO;

UPDATE TCONTRATO SET
DESCONTO = 27
WHERE COD_CONTRATO = 6;

--
SELECT CON.COD_CONTRATO AS CONTRATO, CON.DESCONTO,
       DES.CLASSE AS DESCONTO

FROM TCONTRATO CON, TDESCONTO DES
WHERE CON.DESCONTO BETWEEN DES.INFERIOR AND DES.SUPERIOR

ORDER BY CON.COD_CONTRATO;



--Mostrar cursos vendidos
SELECT CUR.COD_CURSO, CUR.NOME, ITE.VALOR
FROM TCURSO CUR, TITEM ITE
WHERE CUR.COD_CURSO = ITE.COD_CURSO

-Mostrar cursos nao vendidos
SELECT CUR.COD_CURSO, CUR.NOME, ITE.COD_ITEM
FROM TCURSO CUR, TITEM ITE
WHERE CUR.COD_CURSO = ITE.COD_CURSO (+)
AND ITE.COD_ITEM IS NULL;

SELECT * FROM TCURSO;
SELECT * FROM TITEM;

INSERT INTO TCURSO VALUES (6, 'PHP', 1000, 100, NULL);
INSERT INTO TCURSO VALUES (7, 'LOGICA', 100, 20, NULL);

--add coluna em tabela
ALTER TABLE TCURSO ADD PRE_REQ INTEGER;

SELECT * FROM TCURSO;

UPDATE TCURSO SET PRE_REQ = 7
  WHERE COD_CURSO = 1;

UPDATE TCURSO SET PRE_REQ = 7
  WHERE COD_CURSO = 3;

UPDATE TCURSO SET PRE_REQ = 1
  WHERE COD_CURSO = 2;

UPDATE TCURSO SET PRE_REQ = 3
  WHERE COD_CURSO = 4;

UPDATE TCURSO SET PRE_REQ = 7
  WHERE COD_CURSO = 6;

SELECT * FROM TCURSO

--Select de duas tabelas (a mesma tabela)
SELECT CURSO.NOME AS CURSO,
       PRE_REQ.NOME AS PRE_REQUESITO

FROM TCURSO CURSO, TCURSO PRE_REQ
WHERE CURSO.PRE_REQ = PRE_REQ.COD_CURSO(+)







