-----capitulo 09 - Cricao de tabela

CREATE TABLE TESTE
  ( CODIGO INTEGER NOT NULL PRIMARY KEY,
    DATA DATE DEFAULT SYSDATE
  );

SELECT * FROM TESTE;

INSERT INTO TESTE (CODIGO) VALUES (1);

INSERT INTO TESTE (CODIGO, DATA)
VALUES            (2, '13/12/2021');

--tabelas criadas pelo usuario - USER_TABLES (View)
SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES;

CREATE TABLE TCONTRATO_VIP
AS
  SELECT * FROM TCONTRATO
  WHERE TOTAL > 500;

SELECT * FROM TCONTRATO_VIP;

--add coluna na tabela
ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER (5,2);

-alterar coluna
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER (8,2);

--alterar coluna
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12,2);

--Renomear coluna
ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2;

--excluir coluna
ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

--excluir tabela
DROP TABLE TCONTRATO_VIP;

SELECT * FROM USER_TABLES;

COMMIT;

--renomear tabela
RENAME TCONTRATO TO TCONTRATOTOP;

RENAME TCONTRATOTOP TO TCONTRATO;

SELECT * FROM TCONTRATO;




--Comentario na tabela -
COMMENT ON TABLE TCONTRATO IS 'Informações de contratos';

--comentario na coluna da tabela
COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Código do contrato';

COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de emissão do contrato';










